// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.tencent.tars.testtars;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TestMap {

	@TarsStructProperty(order = 0, isRequire = false)
	public String testStr = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.Map<String, String> strMap = null;

	public String getTestStr() {
		return testStr;
	}

	public void setTestStr(String testStr) {
		this.testStr = testStr;
	}

	public java.util.Map<String, String> getStrMap() {
		return strMap;
	}

	public void setStrMap(java.util.Map<String, String> strMap) {
		this.strMap = strMap;
	}

	public TestMap() {
	}

	public TestMap(String testStr, java.util.Map<String, String> strMap) {
		this.testStr = testStr;
		this.strMap = strMap;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(testStr);
		result = prime * result + TarsUtil.hashCode(strMap);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TestMap)) {
			return false;
		}
		TestMap other = (TestMap) obj;
		return (
			TarsUtil.equals(testStr, other.testStr) &&
			TarsUtil.equals(strMap, other.strMap) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != testStr) {
			_os.write(testStr, 0);
		}
		if (null != strMap) {
			_os.write(strMap, 1);
		}
	}

	static java.util.Map<String, String> cache_strMap;
	static { 
		cache_strMap = new java.util.HashMap<String, String>();
		String var_2 = "";
		String var_3 = "";
		cache_strMap.put(var_2 ,var_3);
	}

	public void readFrom(TarsInputStream _is) {
		this.testStr = _is.readString(0, false);
		this.strMap = (java.util.Map<String, String>) _is.read(cache_strMap, 1, false);
	}

}
