// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.tencent.tars.testtars;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TestStruct {

	@TarsStructProperty(order = 0, isRequire = false)
	public String testStr = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public TestMap testMap = null;

	public String getTestStr() {
		return testStr;
	}

	public void setTestStr(String testStr) {
		this.testStr = testStr;
	}

	public TestMap getTestMap() {
		return testMap;
	}

	public void setTestMap(TestMap testMap) {
		this.testMap = testMap;
	}

	public TestStruct() {
	}

	public TestStruct(String testStr, TestMap testMap) {
		this.testStr = testStr;
		this.testMap = testMap;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(testStr);
		result = prime * result + TarsUtil.hashCode(testMap);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TestStruct)) {
			return false;
		}
		TestStruct other = (TestStruct) obj;
		return (
			TarsUtil.equals(testStr, other.testStr) &&
			TarsUtil.equals(testMap, other.testMap) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != testStr) {
			_os.write(testStr, 0);
		}
		if (null != testMap) {
			_os.write(testMap, 1);
		}
	}

	static TestMap cache_testMap;
	static { 
		cache_testMap = new TestMap();
	}

	public void readFrom(TarsInputStream _is) {
		this.testStr = _is.readString(0, false);
		this.testMap = (TestMap) _is.read(cache_testMap, 1, false);
	}

}
